# Name of workflow as seen in Github actions tab
name: dev-build-and-deploy
# Run workflow only on push to dev branch
on:
  push:
    branches:
      - develop
jobs:
  # To build the project
  build-tambola:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create Bucket if not exist
        run: aws s3api head-bucket --bucket demo-impact-hub-${NEXT_PUBLIC_ENV} 2> /dev/null || aws s3api create-bucket --bucket demo-impact-hub-${NEXT_PUBLIC_ENV} --region us-east-1

      - name: Deploy to S3 bucket
        run: echo $NEXT_PUBLIC_ENV && aws s3 sync ./out/ s3://demo-impact-hub-${NEXT_PUBLIC_ENV} --delete
