# .github/workflows/example-2.yml

name: Manual Inputs
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Example variable usage
        run: |
          git remote set-url --push origin https://vengleab:$GITHUB_TOKEN@github.com/vengleab/demo-impact-hub/
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

